name: Deploy on productive

on:
  pull_request:
    branches: ["main"]

jobs:

  deploy_server_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.APP_ID }}
          api_key: ${{ secrets.APP_KEY }}
          wait_deploy: true
          github_token: ''
